### ISSUE TITLE
Error on line 13: 

### ISSUE THREAD

**Issue by akindipe** [anshumanpillai/Twitter-Sentiment-Analysis#1]

**Comment by akindipe** [comment]
combi ['tidy_tweet']=np.vectorize(remove_pattern)(combi[str("tweet")],"@[\w]*")

![Screen Shot 2021-08-23 at 13 26 13](https://user-images.githubusercontent.com/11035792/130447100-7bf5d9ca-0b72-45f5-9814-4d28c8026ad5.png)

**Comment by anshumanpillai** [comment]
if you remove the str function then it will work fine

**Comment by akindipe** [comment]
I have removed it and kept getting the same error
![Screen Shot 2021-08-23 at 14 51 15](https://user-images.githubusercontent.com/11035792/130459127-84aa183d-e3c1-4dcb-8a43-1ff5117647d1.png)

**Comment by akindipe** [comment]
This is the ipynb file in pdf
[sentiment_analysis - Colaboratory.pdf](https://github.com/anshumanpillai/Twitter-Sentiment-Analysis/files/7032893/sentiment_analysis.-.Colaboratory.pdf)
